[build]
  command = "./build.sh"
  functions = "functions"
  publish = "app/templates"

[build.environment]
  GO_IMPORT_PATH = "https://github.com/khaletska/tetris"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200